# Generated by Django 5.2.1 on 2025-06-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('sender_email', models.CharField(max_length=255)),
                ('cc', models.CharField(max_length=255)),
                ('bcc', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('html_body', models.TextField()),
            ],
        ),
    ]
