# Generated by Django 5.2.1 on 2025-06-05 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 19, 0)),
            preserve_default=False,
        ),
    ]
