# Generated by Django 5.2.1 on 2025-06-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_email_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='sender_email',
        ),
    ]
