# Generated by Django 5.2.1 on 2025-06-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_remove_email_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='negative',
            field=models.DecimalField(decimal_places=4, default=-1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='neutral',
            field=models.DecimalField(decimal_places=4, default=-1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='positive',
            field=models.DecimalField(decimal_places=4, default=-1, max_digits=5),
            preserve_default=False,
        ),
    ]
