# Generated by Django 5.2.1 on 2025-06-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_email_negative_email_neutral_email_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='hash',
            field=models.CharField(default='x', max_length=64),
            preserve_default=False,
        ),
    ]
