# Generated by Django 5.2.1 on 2025-06-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_email_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
